Web/BuscadorCEP/Controllers/BuscarCepController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BuscadorCEP.Controllers
{
	public class BuscarCepController : Controller
	{
		[Route("BuscadorCEP/BuscarCEP")]
		public ActionResult Index()
		{
			List<KeyValuePair<string, string>> estados = PreencheEstados();

			ViewBag.Estados = estados;

			return View();
		}

		private List<KeyValuePair<string, string>> PreencheEstados()
		{
			List<KeyValuePair<string, string>> estados = new List<KeyValuePair<string, string>>();

			estados.Add(new KeyValuePair<string, string>("AC", "Acre"));
			estados.Add(new KeyValuePair<string, string>("AL", "Alagoas"));
			estados.Add(new KeyValuePair<string, string>("AP", "Amapa"));
			estados.Add(new KeyValuePair<string, string>("AM", "Amazonas"));
			estados.Add(new KeyValuePair<string, string>("BA", "Bahia"));
			estados.Add(new KeyValuePair<string, string>("CE", "Ceara"));
			estados.Add(new KeyValuePair<string, string>("DF", "Distrito Federal"));
			estados.Add(new KeyValuePair<string, string>("ES", "Espirito Santo"));
			estados.Add(new KeyValuePair<string, string>("GO", "Goias"));
			estados.Add(new KeyValuePair<string, string>("MA", "Maranhao"));
			estados.Add(new KeyValuePair<string, string>("MT", "Mato Grosso"));
			estados.Add(new KeyValuePair<string, string>("MS", "Mato Grosso do Sul"));
			estados.Add(new KeyValuePair<string, string>("MG", "Minas Gerais"));
			estados.Add(new KeyValuePair<string, string>("PA", "Para"));
			estados.Add(new KeyValuePair<string, string>("PB", "Paraiba"));
			estados.Add(new KeyValuePair<string, string>("PR", "Parana"));
			estados.Add(new KeyValuePair<string, string>("PE", "Pernambuco"));
			estados.Add(new KeyValuePair<string, string>("PI", "Piaui"));
			estados.Add(new KeyValuePair<string, string>("RJ", "Rio de Janeiro"));
			estados.Add(new KeyValuePair<string, string>("RN", "Rio Grande do Norte"));
			estados.Add(new KeyValuePair<string, string>("RS", "Rio Grande do Sul"));
			estados.Add(new KeyValuePair<string, string>("RO", "Rondonia"));
			estados.Add(new KeyValuePair<string, string>("RR", "Roraima"));
			estados.Add(new KeyValuePair<string, string>("SC", "Santa Catarina"));
			estados.Add(new KeyValuePair<string, string>("SP", "Sao Paulo"));
			estados.Add(new KeyValuePair<string, string>("SE", "Sergipe"));
			estados.Add(new KeyValuePair<string, string>("TO", "Tocantins"));

			return estados;
		}
	}
}

Web/BuscadorCEP/Controllers/BuscarEnderecoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BuscadorCEP.Controllers
{
	public class BuscarEnderecoController : Controller
	{
		[Route("BuscadorCEP/BuscarEndereco/{cep?}")]
		public ActionResult Index(string cep)
		{
			if (cep == null)
				return View();
			else
			{
				ViewBag.Cep = cep;
				return View("Resultado");
			}
		}
	}
}

Web/BuscadorCEP/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BuscadorCEP.Controllers
{
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			return View();
		}
	}
}

Web/BuscadorCEP/Views/BuscarCep/Index.cshtml
@{
    ViewData["Title"] = "Buscar Cep";
}

<div class="mt-2">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="@(Url.Action("Index","Home"))">Início</a></li>
            <li class="breadcrumb-item active" aria-current="page">Buscar CEP</li>
        </ol>
    </nav>
    <div class="mt-4">
        <div class="mb-3 col-3">
            <label class="form-label">Estado</label>
            <select id="estado-select" class="form-select">
                <option hidden>Escolha um estado...</option>
                @{
                    foreach (var estado in ViewBag.Estados)
                    {
                        <option value="@estado.Key" id="@estado.Key">@estado.Value</option>
                    }
                }
            </select>
        </div>
        <div class="mb-3 col-3">
            <label class="form-label">Município</label>
            <select id="municipio-select" class="form-select" disabled>
                <option hidden>Escolha um município...</option>
            </select>
        </div>
        <div class="mb-3 col-3">
            <label class="form-label">Logradouro</label>
            <select id="logradouro-select" class="form-select" disabled>
                <option hidden>Escolha um logradouro...</option>
            </select>
        </div>
    </div>
    <div class="d-flex gap-4 mt-3">
        <button class="btn btn-secondary" onclick="window.location.pathname = '@(Url.Action("Index","Home"))'">Voltar</button>
        <button class="btn btn-primary" onclick="BuscaCep()" data-bs-toggle="modal" data-bs-target="#cep-modal">Pesquisar</button>
    </div>
</div>

<div id="cep-modal" class="modal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Cep</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row g-2">
                    <div class="col-auto">
                        <label class="form-label fw-bold">CEP:</label>
                    </div>
                    <div class="col-auto">
                        <p id="cep-p"></p>
                    </div>
                </div>
                <div class="row g-2">
                    <div class="col-auto">
                        <label class="form-label fw-bold">Código do logradouro:</label>
                    </div>
                    <div class="col-auto">
                        <p id="codLogradouro-p"></p>
                    </div>
                </div>
                <div class="row g-2">
                    <div class="col-auto">
                        <label class="form-label fw-bold">Município:</label>
                    </div>
                    <div class="col-auto">
                        <p id="municipio-p"></p>
                    </div>
                </div>
                <div class="row g-2">
                    <div class="col-auto">
                        <label class="form-label fw-bold">Logradouro:</label>
                    </div>
                    <div class="col-auto">
                        <p id="logradouro-p"></p>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Ok</button>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    <script src="~/Scripts/Views/BuscarCep/Index.js"></script>
}

Web/BuscadorCEP/Views/BuscarEndereco/Index.cshtml
@{
	ViewData["Title"] = "Buscar Endereço";
}

<div class="mt-2">
	<nav aria-label="breadcrumb">
		<ol class="breadcrumb">
			<li class="breadcrumb-item"><a href="@(Url.Action("Index","Home"))">Início</a></li>
			<li class="breadcrumb-item active" aria-current="page">Buscar Endereço</li>
		</ol>
	</nav>
	<div class="mt-4">
		<div class="mb-3 col-3">
			<label class="form-label">CEP <strong>*</strong></label>
			<input id="cep-input" maxlength="8" class="form-control" type="text" placeholder="Ex: 13700000">
		</div>
	</div>
	<div class="d-flex gap-4 mt-3">
		<button class="btn btn-secondary" onclick="window.location.pathname = '@(Url.Action("Index","Home"))'">Voltar</button>
		<button id="buscar-button" class="btn btn-primary">Buscar</button>
	</div>
</div>

@section Scripts {
	<script src="~/Scripts/Views/BuscarEndereco/Index.js"></script>
}

Web/BuscadorCEP/Views/BuscarEndereco/Resultado.cshtml
@{
    ViewData["Title"] = "Endereço";
}

<div class="mt-2">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="@(Url.Action("Index","Home"))">Início</a></li>
            <li class="breadcrumb-item"><a href="@(Url.Action("Index","BuscarEndereco"))">Buscar Endereço</a></li>
            <li class="breadcrumb-item active" aria-current="page">Resultado - @ViewBag.Cep</li>
        </ol>
    </nav>
    <div class="mt-4">
        <div class="mb-3 col-3">
            <label class="form-label">Logradouro</label>
            <input id="logradouro-input" class="form-control" disabled>
        </div>
        <div class="mb-3 col-3">
            <label class="form-label">Município/ UF</label>
            <input id="municipio-input" class="form-control" disabled>
        </div>
        <div class="mb-3 col-3">
            <label class="form-label">Bairro</label>
            <input id="bairro-input" class="form-control" disabled>
        </div>
        <div class="mb-3 col-3">
            <label class="form-label">CEP</label>
            <input value="@ViewBag.Cep" id="cep-input" class="form-control" disabled>
        </div>
    </div>
    <div class="d-flex gap-4 mt-3">
        <button class="btn btn-primary" onclick="window.location.href = `${window.location.origin}${window.location.pathname}`">Nova Busca</button>
        <button class="btn btn-secondary" onclick="window.print()" >Imprimir</button>
    </div>
</div>

@section Scripts {
    <script src="~/Scripts/Views/BuscarEndereco/Resultado.js"></script>
}

Web/BuscadorCEP/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<div class="mt-5">
    <h1 class="fw-bold">Bem vindo ao BuscadorCEP!</h1>
    <div class="mt-3">
        <p>O aplicativo BuscadorCEP! permite que você encontre códigos de endereçamento postais (CEP).</p>
        <p>Se você já tiver o CEP em mãos e gostaria de buscar seu endereço, o BuscadorCEP! também vai te ajudar.</p>
        <p>Aproveite :D</p>
    </div>
    <div class="d-flex gap-4 mt-3">
        <button class="btn btn-primary" onclick="window.location.pathname = '@(Url.Action("Index","BuscarEndereco"))'">Buscar Endereço</button>
        <button class="btn btn-primary" onclick="window.location.pathname = '@(Url.Action("Index","BuscarCep"))'">Buscar CEP</button>
    </div>
</div>

Web/BuscadorCEP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - BuscadorCEP</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" href="@(Url.Action("Index","Home"))">BuscadorCEP</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between ms-5">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="@(Url.Action("Index","BuscarEndereco"))">Buscar Endereço</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="@(Url.Action("Index","BuscarCep"))">Buscar CEP</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container ms-5">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container-fluid">
            @DateTime.Now.Year - BuscadorCEP!
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @RenderSection("scripts", required: false)
    <script>
      let apiUrl = '@System.Configuration.ConfigurationManager.AppSettings["ApiUrl"]';
    </script>
</body>
</html>